const Musics = [
  {
    id: '1',
    imgAlbum:
      'https://i.scdn.co/image/ab67616d00004851f907de96b9a4fbc04accc0d5',
    musicName: "God's Plan",
    singerName: 'Drake',
    albumName: 'Scorpion',
    timestamp: '3:19',
  },
  {
    id: '2',
    imgAlbum:
      'https://i.scdn.co/image/ab67616d0000485105a448540b069450ccfba889',
    musicName: 'WHATS POPPIN',
    singerName: 'Jack Harlow',
    albumName: 'Sweet Action',
    timestamp: '2:20',
  },
  {
    id: '3',
    imgAlbum:
      'https://i.scdn.co/image/ab67616d00004851f54b99bf27cda88f4a7403ce',
    musicName: 'goosebumps',
    singerName: 'Travis Scott',
    albumName: 'Birds in The Trap Sing Mcknight',
    timestamp: '4:04',
  },
  {
    id: '4',
    imgAlbum:
      'https://i.scdn.co/image/ab67616d00004851072e9faef2ef7b6db63834a3',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '5',
    imgAlbum: 'https://picsum.photos/201',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '6',
    imgAlbum: 'https://picsum.photos/202',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '7',
    imgAlbum: 'https://picsum.photos/203',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '8',
    imgAlbum: 'https://picsum.photos/204',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '9',
    imgAlbum: 'https://picsum.photos/205',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '10',
    imgAlbum: 'https://picsum.photos/206',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '11',
    imgAlbum: 'https://picsum.photos/207',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '12',
    imgAlbum: 'https://picsum.photos/208',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '13',
    imgAlbum: 'https://picsum.photos/209',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '14',
    imgAlbum: 'https://picsum.photos/210',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '15',
    imgAlbum: 'https://picsum.photos/211',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '16',
    imgAlbum: 'https://picsum.photos/212',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '17',
    imgAlbum: 'https://picsum.photos/213',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '18',
    imgAlbum: 'https://picsum.photos/214',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '19',
    imgAlbum: 'https://picsum.photos/215',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
  {
    id: '20',
    imgAlbum: 'https://picsum.photos/216',
    musicName: 'SICKO MODE',
    singerName: 'Travis Scott',
    albumName: 'ASTROWORLD',
    timestamp: '5:13',
  },
];

export default Musics;
