const PlaylistNames = [
  { id: '0', name: 'Ahsiudhiuashd' },
  { id: '1', name: 'Vejaa' },
  { id: '2', name: 'Dale' },
  { id: '3', name: 'Ahaa' },
  { id: '4', name: 'Esquece' },
  { id: '5', name: 'É us gu' },
  { id: '6', name: 'Teste' },
  { id: '7', name: 'Manda' },
  { id: '8', name: 'Pufff' },
  { id: '9', name: 'Pacheco' },
  { id: '10', name: 'Junior' },
  { id: '11', name: 'Daleee' },
  { id: '12', name: 'Mirandinha' },
  { id: '13', name: 'João' },
  { id: '14', name: 'Revoada' },
  { id: '15', name: 'Megafunk' },
  { id: '16', name: 'Manu' },
  { id: '17', name: 'Laura' },
  { id: '18', name: 'Tatim' },
  { id: '19', name: 'Luisa' },
  { id: '20', name: 'Lucca' },
  { id: '21', name: 'Periclitante' },
  { id: '22', name: 'Roberta' },
  { id: '23', name: 'Raquel' },
  { id: '24', name: 'Duque' },
  { id: '25', name: 'Julinha' },
  { id: '26', name: 'Ricardo' },
  { id: '27', name: 'Buda' },
];

export default PlaylistNames;
